version: 0.2

phases:

  pre_build:
    commands:
      - cd serverless-app-sam/
      - sam validate
      - echo "✅ SAM template validated"

  build:
    commands:
      - echo "AWS SAM starting the build."
      - sam build
      - echo "Deploying to env '$Environment'"
      # Create unique S3 bucket name based on environment and timestamp
      - UNIQUE_SUFFIX=$(date +%s | tail -c 6)
      - S3_BUCKET="aws-sam-cli-managed-${Environment}-${UNIQUE_SUFFIX}"
      
      # Deploy with unique bucket
      - sam deploy --config-env $Environment --s3-bucket $S3_BUCKET --no-confirm-changeset
      
      # Get stack name
      - STACK_NAME="serverless-app-crawler-sam-$Environment"
      - echo "Stack name '$STACK_NAME'"

  post_build:
    commands:
      # sam delete --config-env dev --no-prompts

