version: 0.2

phases:

  pre_build:
    commands:
      - cd serverless-app-sam/
      - sam validate
      - echo "✅ SAM template validated"

  build:
    commands:
      - echo "AWS SAM starting the build."
      - sam build
      - echo "Deploying to env '$Environment'"
      - sam deploy --config-env $Environment 
      # Extract stack name from samconfig.toml based on environment
      - STACK_NAME=$(grep -A 10 "\[$Environment.deploy.parameters\]" samconfig.toml | grep "stack_name" | cut -d'"' -f2)
      - echo "Stack name '$STACK_NAME'"

  post_build:
    commands:
      - sam delete --config-env dev --no-prompts

