version: 0.2

phases:

  pre_build:
    commands:
      - echo "$Enviroment"
      #- python3 --version
      #- pip3 --version
      - cd serverless-app-sam/
      - sam validate
      - echo "✅ SAM template validated"

  build:
    commands:
      - sam build
      - echo "Build complete"

  post_build:
    commands:
      - echo "Build complete"
      # Optional deployment if needed:
      # - sam deploy --stack-name "serverless-app-crawler-sam-$Enviroment" --capabilities CAPABILITY_IAM --region eu-north-1 --no-confirm-changeset
