version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Updating system packages"
      - sudo yum update -y

  pre_build:
    commands:
      - echo "$ENVIRONMENT"
      - python3 --version
      - pip3 --version
      - cd serverless-app-sam/
      - sam --version
      - sam validate
      - echo "✅ SAM template validated"

  build:
    commands:
      - sam build

  post_build:
    commands:
      - echo "Build complete"
      # Optional deployment if needed:
      # - sam deploy --stack-name webcrawler-dev --capabilities CAPABILITY_IAM --region eu-central-1 --no-confirm-changeset
