version: 0.2

phases:

  pre_build:
    commands:
      - echo "AWS SAM starting deployment to '$Environment'"

  build:
    commands:
      - ./codepipeline/scripts/deploy.sh

  post_build:
    commands:
      - echo "Deployment to '$Environment' completed successfully."

  artifacts:
    files:
      - '**/*'
    base-directory: serverless-app-sam
    name: BuildArtifacts
