version: 0.2

cache:
  paths:
    - '.cache/pip/**/*'        # Python pip cache
    - '.npm/**/*'              # npm cache (for jq, etc.)

phases:

  pre_build:
    commands:
      - echo "Preparing for integration tests on '$Environment'"

  build:
    commands:
      - echo "Running integration tests..."
      - ./codepipeline/scripts/integration_test.sh

  post_build:
    commands:
      - cd serverless-app-sam 
      - echo "📋 Test Summary:"
      - echo "📄 Lambda Response:"
      - cat events/response_initiator_lambda.json || echo "No lambda response"
      - echo "📄 DynamoDB Records:"
      - cat events/response_dynamodb_table.json | jq '.Count' || echo "No DynamoDB data"

artifacts:
  files:
    - 'serverless-app-sam/events/**/*'     # Test event files
    - 'serverless-app-sam/response/**/*'   # Test response files  
    - 'codepipeline/**/*'
  name: TestResults
