version: 0.2

phases:

  pre_build:
    commands:
      - echo "AWS SAM starting the build."

  build:
    commands:
      - ./codepipeline/scripts/build.sh
      
  post_build:
    commands:
      - echo "End of build phase"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

