version: 0.2

cache:
  paths:
    - '/root/.cache/pip/**/*'        # Python pip cache
    - '/root/.aws/**/*'              # AWS CLI cache
    - '/root/.sam/**/*'              # SAM CLI cach

phases:
  install:
    commands:
      - echo "📦 Installing SAM CLI..."
      - pip install aws-sam-cli==1.142.1

  pre_build:
    commands:
      - echo "AWS SAM starting deployment to '$Environment'"

  build:
    commands:
      - ./codepipeline/scripts/deploy.sh

  post_build:
    commands:
      - echo "Deployment to '$Environment' completed successfully."

artifacts:
  files:
    - 'serverless-app-sam/cfn-outputs.json'
    - 'serverless-app-sam/cfn-outputs-simple.json'
    - 'serverless-app-sam/events/**/*'
    - 'codepipeline/**/*'
  name: DeployArtifacts
