version: 0.2

phases:

  pre_build:
    commands:
      - echo "Preparing for integration tests on '$Environment'"

  build:
    commands:
      - echo "Running integration tests..."
      - ./codepipeline/scripts/integration_test.sh

  post_build:
    commands:
      - echo "📋 Test  Summary:"
      - echo "📄 Lambda Response:"
      - cat serverless-app-sam/events/response_initiator_lambda.json || echo "No lambda response"
      - echo "📄 DynamoDB Records:"
      - cat serverless-app-sam/events/response_dynamodb_table.json | jq '.Count' || echo "No DynamoDB data"

artifacts:
  files:
    - 'serverless-app-sam/events/**/*'     # Test event files
    - 'serverless-app-sam/response/**/*'   # Test response files  
    - 'codepipeline/**/*'
  name: TestResults
