version: 0.2

cache:
  paths:
    - '.cache/pip/**/*'        # Python pip cache
    - '.aws/**/*'              # AWS CLI cache
    - '.sam/**/*'              # SAM CLI cach

phases:

  pre_build:
    commands:
      - echo "AWS SAM starting deployment to '$Environment'"

  build:
    commands:
      - ./codepipeline/scripts/deploy.sh

  post_build:
    commands:
      - echo "Deployment to '$Environment' completed successfully."

artifacts:
  files:
    - 'serverless-app-sam/cfn-outputs.json'
    - 'serverless-app-sam/cfn-outputs-simple.json'
    - 'serverless-app-sam/events/**/*'
    - 'codepipeline/**/*'
  name: DeployArtifacts
