# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
region = "eu-north-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

# ─── DEV ENVIRONMENT ───────────────────────────────────────────────────────────
[dev.deploy.parameters]
stack_name = "serverless-app-crawler-sam-dev"
parameter_overrides = "Environment=dev"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "serverless-app-crawler-sam"
image_repositories = []
confirm_changeset = false
no_confirm_changeset = true

# ─── PROD ENVIRONMENT ──────────────────────────────────────────────────────────
[prod.deploy.parameters]
stack_name           = "serverless-app-crawler-sam-prod"
parameter_overrides  = "Environment=prod"
capabilities         = "CAPABILITY_IAM"
resolve_s3           = true
s3_prefix            = "serverless-app-crawler-sam"
image_repositories   = []
confirm_changeset    = false
no_confirm_changeset = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
